# Generated by Django 3.1 on 2020-08-21 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0007_auto_20200821_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedHotels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unique_snippet', models.CharField(max_length=500)),
                ('details', models.CharField(max_length=2000)),
                ('booking_website', models.URLField()),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=75)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuggestedHotelPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_forms.suggestedhotels')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
