# Generated by Django 3.1 on 2020-08-21 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestedhotels',
            name='country',
        ),
        migrations.DeleteModel(
            name='SuggestedHotelPhotos',
        ),
        migrations.DeleteModel(
            name='SuggestedHotels',
        ),
    ]
