# Generated by Django 3.1 on 2020-08-16 11:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='liked_by_user',
            field=models.ManyToManyField(related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hotels',
            name='rejected_by_user',
            field=models.ManyToManyField(related_name='rejected', to=settings.AUTH_USER_MODEL),
        ),
    ]
