# Generated by Django 3.1 on 2020-08-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20200816_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='booking_website',
            field=models.URLField(default='www.yumveganlunchideas.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=12.32, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='lon',
            field=models.DecimalField(decimal_places=6, default=234.4234, max_digits=9),
            preserve_default=False,
        ),
    ]
