# Generated by Django 3.1 on 2020-08-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_auto_20200819_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='hotel',
            field=models.ManyToManyField(blank=True, to='hotels.Hotels'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='hotel',
            field=models.ManyToManyField(blank=True, to='hotels.Hotels'),
        ),
    ]
