# Generated by Django 3.1 on 2020-08-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_hotels_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='contact_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
