# Generated by Django 3.1 on 2020-08-16 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlikedhotels',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='userlikedhotels',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userrejectedhotels',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='userrejectedhotels',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserLastViewedHotel',
        ),
        migrations.DeleteModel(
            name='UserLikedHotels',
        ),
        migrations.DeleteModel(
            name='UserRejectedHotels',
        ),
    ]
